const express=require('express');const crypto=require('crypto');const pool=require('../db/pool');const {requireAuth,requireRole}=require('../middleware/auth');const audit=require('../middleware/audit');const {text,uuid,oneOf}=require('../validators/common');const {runAutomations}=require('../services/automation');
const router=express.Router();router.use(requireAuth);const triggers=['TASK_DUE','TASK_OVERDUE','APPROVAL_PENDING','CONTENT_SCHEDULED','CAMPAIGN_START'];
router.get('/',async(req,res,next)=>{try{const r=await pool.query(`SELECT r.*,COALESCE((SELECT COUNT(*) FROM automation_runs x WHERE x.rule_id=r.id),0)::int run_count FROM automation_rules r ORDER BY r.created_at DESC`);res.json({data:r.rows})}catch(e){next(e)}});
router.post('/',requireRole('ADMIN','MANAGER'),async(req,res,next)=>{try{const name=text(req.body.name,180);const trigger=oneOf(req.body.trigger_type,triggers);const r=await pool.query(`INSERT INTO automation_rules(id,name,description,trigger_type,action_type,conditions,action_config,created_by) VALUES($1,$2,$3,$4,'IN_APP_NOTIFICATION',$5,$6,$7) RETURNING *`,[crypto.randomUUID(),name,req.body.description?text(req.body.description,3000):null,trigger,req.body.conditions||{},req.body.action_config||{},req.user.id]);await audit(req,{action:'CREATE',entity:'automation_rule',entityId:r.rows[0].id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]})}catch(e){next(e)}});
router.patch('/:id',requireRole('ADMIN','MANAGER'),async(req,res,next)=>{try{const id=uuid(req.params.id);const r=await pool.query(`UPDATE automation_rules SET is_active=COALESCE($1,is_active),name=COALESCE($2,name),description=COALESCE($3,description),updated_at=NOW() WHERE id=$4 RETURNING *`,[req.body.is_active===undefined?null:Boolean(req.body.is_active),req.body.name?text(req.body.name,180):null,req.body.description?text(req.body.description,3000):null,id]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND',message:'Automação não encontrada.'});await audit(req,{action:'UPDATE',entity:'automation_rule',entityId:id,afterData:r.rows[0]});res.json({data:r.rows[0]})}catch(e){next(e)}});
router.post('/run',requireRole('ADMIN','MANAGER'),async(req,res,next)=>{try{res.json({data:await runAutomations()})}catch(e){next(e)}});

router.delete('/:id',requireRole('ADMIN','MANAGER'),async(req,res,next)=>{try{const id=uuid(req.params.id);const before=(await pool.query('SELECT * FROM automation_rules WHERE id=$1',[id])).rows[0];if(!before)return res.status(404).json({error:'NOT_FOUND',message:'Automação não encontrada.'});await pool.query('DELETE FROM automation_rules WHERE id=$1',[id]);await audit(req,{action:'DELETE',entity:'automation_rule',entityId:id,beforeData:before});res.status(204).end()}catch(e){next(e)}});
module.exports=router;
