const express=require('express');
const crypto=require('crypto');
const pool=require('../db/pool');
const {requireAuth,requireRole}=require('../middleware/auth');
const audit=require('../middleware/audit');

const router=express.Router();
router.use(requireAuth);

const ROLES={write:['ADMIN','STAKEHOLDER','MANAGER','USER'],delete:['ADMIN']};
const leadStatuses=new Set(['NEW','QUALIFICATION','MQL','SQL','DEMO','WON','LOST','NURTURE']);
const allowedTransitions={
  NEW:new Set(['QUALIFICATION','LOST','NURTURE']),
  QUALIFICATION:new Set(['MQL','SQL','LOST','NURTURE']),
  MQL:new Set(['SQL','DEMO','LOST','NURTURE']),
  SQL:new Set(['DEMO','WON','LOST','NURTURE']),
  DEMO:new Set(['WON','LOST','NURTURE']),
  WON:new Set([]),
  LOST:new Set(['NURTURE','QUALIFICATION']),
  NURTURE:new Set(['QUALIFICATION','MQL','LOST'])
};
const companyStatuses=new Set(['ACTIVE','INACTIVE','PROSPECT','CUSTOMER']);
const companySizes=new Set(['MICRO','SMALL','MEDIUM','LARGE']);
const contactRoles=new Set(['DECISION_MAKER','INFLUENCER','USER','FINANCIAL','TECHNICAL','OTHER']);
const contactStatuses=new Set(['ACTIVE','INACTIVE']);

function cleanString(value,max=255){if(value===undefined||value===null)return null;const v=String(value).trim();return v? v.slice(0,max):null;}
function uuid(value){return typeof value==='string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);}
function positiveInt(value, fallback, max){const n=Number(value);if(!Number.isInteger(n)||n<1)return fallback;return Math.min(n,max);}
function canWrite(req,entity){return ROLES.write.includes(req.user?.role) && (req.user.role==='ADMIN'||req.user.role==='STAKEHOLDER'||req.user.role==='MANAGER'||!entity?.owner_id||entity.owner_id===req.user.id);}
function canDelete(req){return ROLES.delete.includes(req.user?.role);}
function parseLimitOffset(req){const limit=positiveInt(req.query.limit,25,100);const page=positiveInt(req.query.page,1,1000000);return {limit,page,offset:(page-1)*limit};}
function like(value){return `%${String(value||'').trim()}%`;}

router.get('/lead-sources',async(req,res,next)=>{try{const r=await pool.query('SELECT id,name,type,active,created_at,updated_at FROM lead_sources WHERE active=true ORDER BY name');res.json({data:r.rows});}catch(e){next(e)}});

router.get('/companies',async(req,res,next)=>{try{
  const {limit,page,offset}=parseLimitOffset(req); const values=[]; const where=[];
  if(req.query.search){values.push(like(req.query.search));where.push(`(trade_name ILIKE $${values.length} OR COALESCE(legal_name,'') ILIKE $${values.length} OR COALESCE(document_number,'') ILIKE $${values.length})`)}
  if(companyStatuses.has(String(req.query.status||''))){values.push(req.query.status);where.push(`status=$${values.length}`)}
  if(uuid(req.query.owner_id)){values.push(req.query.owner_id);where.push(`owner_id=$${values.length}`)}
  const clause=where.length?`WHERE ${where.join(' AND ')}`:'';
  const count=await pool.query(`SELECT COUNT(*)::int AS total FROM companies ${clause}`,values);
  values.push(limit,offset);
  const r=await pool.query(`SELECT * FROM companies ${clause} ORDER BY updated_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);
  res.json({data:{items:r.rows,pagination:{page,limit,total:count.rows[0].total}}});
}catch(e){next(e)}});

router.post('/companies',async(req,res,next)=>{try{
  if(!canWrite(req))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});
  const tradeName=cleanString(req.body?.trade_name,180); if(!tradeName)return res.status(400).json({error:'INVALID_INPUT',message:'Nome fantasia é obrigatório.'});
  const status=cleanString(req.body?.status,30)||'ACTIVE'; if(!companyStatuses.has(status))return res.status(400).json({error:'INVALID_INPUT',message:'Status de empresa inválido.'});
  const size=cleanString(req.body?.company_size,30); if(size&&!companySizes.has(size))return res.status(400).json({error:'INVALID_INPUT',message:'Porte inválido.'});
  const stores=req.body?.store_count==null?null:Number(req.body.store_count); if(stores!==null&&(!Number.isInteger(stores)||stores<0||stores>100000))return res.status(400).json({error:'INVALID_INPUT',message:'Número de lojas inválido.'});
  const id=crypto.randomUUID();
  const r=await pool.query(`INSERT INTO companies(id,legal_name,trade_name,document_number,industry,company_size,store_count,website,phone,whatsapp,email,address_line,city,state,postal_code,notes,status,owner_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING *`,[id,cleanString(req.body.legal_name,220),tradeName,cleanString(req.body.document_number,30),cleanString(req.body.industry,120),size,stores,cleanString(req.body.website,500),cleanString(req.body.phone,40),cleanString(req.body.whatsapp,40),cleanString(req.body.email,180),cleanString(req.body.address_line,220),cleanString(req.body.city,120),cleanString(req.body.state,2)?.toUpperCase(),cleanString(req.body.postal_code,12),cleanString(req.body.notes,5000),status,uuid(req.body.owner_id)?req.body.owner_id:req.user.id,req.user.id]);
  await audit(req,{action:'CREATE',entity:'company',entityId:id,afterData:r.rows[0]}); res.status(201).json({data:r.rows[0]});
}catch(e){next(e)}});

router.get('/companies/:id',async(req,res,next)=>{try{if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const r=await pool.query('SELECT * FROM companies WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND',message:'Empresa não encontrada.'});res.json({data:r.rows[0]});}catch(e){next(e)}});

router.patch('/companies/:id',async(req,res,next)=>{try{if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const current=(await pool.query('SELECT * FROM companies WHERE id=$1',[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Empresa não encontrada.'});if(!canWrite(req,current))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});
  const fields={legal_name:['legal_name',220],trade_name:['trade_name',180],document_number:['document_number',30],industry:['industry',120],website:['website',500],phone:['phone',40],whatsapp:['whatsapp',40],email:['email',180],address_line:['address_line',220],city:['city',120],state:['state',2],postal_code:['postal_code',12],notes:['notes',5000],status:['status',30],company_size:['company_size',30]};
  const sets=[];const values=[];for(const [key,[column,max]] of Object.entries(fields)){if(req.body?.[key]!==undefined){let v=cleanString(req.body[key],max);if(key==='state'&&v)v=v.toUpperCase();if(key==='status'&&!companyStatuses.has(v))return res.status(400).json({error:'INVALID_INPUT',message:'Status de empresa inválido.'});if(key==='company_size'&&v&&!companySizes.has(v))return res.status(400).json({error:'INVALID_INPUT',message:'Porte inválido.'});sets.push(`${column}=$${values.length+1}`);values.push(v);}}
  if(req.body?.store_count!==undefined){const n=req.body.store_count==null?null:Number(req.body.store_count);if(n!==null&&(!Number.isInteger(n)||n<0||n>100000))return res.status(400).json({error:'INVALID_INPUT',message:'Número de lojas inválido.'});sets.push(`store_count=$${values.length+1}`);values.push(n);}
  if(uuid(req.body?.owner_id)){sets.push(`owner_id=$${values.length+1}`);values.push(req.body.owner_id)}
  if(!sets.length)return res.json({data:current}); sets.push('updated_at=NOW()');values.push(req.params.id);const r=await pool.query(`UPDATE companies SET ${sets.join(',')} WHERE id=$${values.length} RETURNING *`,values);await audit(req,{action:'UPDATE',entity:'company',entityId:req.params.id,beforeData:current,afterData:r.rows[0]});res.json({data:r.rows[0]});
}catch(e){next(e)}});

router.delete('/companies/:id',async(req,res,next)=>{try{if(!canDelete(req))return res.status(403).json({error:'FORBIDDEN',message:'Somente administradores podem excluir empresas.'});if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const current=(await pool.query('SELECT * FROM companies WHERE id=$1',[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Empresa não encontrada.'});await pool.query('DELETE FROM companies WHERE id=$1',[req.params.id]);await audit(req,{action:'DELETE',entity:'company',entityId:req.params.id,beforeData:current});res.status(204).end();}catch(e){next(e)}});

router.get('/contacts',async(req,res,next)=>{try{
  const {limit,page,offset}=parseLimitOffset(req);const values=[];const where=[];
  if(req.query.search){values.push(like(req.query.search));where.push(`(name ILIKE $${values.length} OR COALESCE(email,'') ILIKE $${values.length} OR COALESCE(whatsapp,'') ILIKE $${values.length})`)}
  if(uuid(req.query.company_id)){values.push(req.query.company_id);where.push(`company_id=$${values.length}`)}
  if(contactRoles.has(String(req.query.role_type||''))){values.push(req.query.role_type);where.push(`role_type=$${values.length}`)}
  if(contactStatuses.has(String(req.query.status||''))){values.push(req.query.status);where.push(`status=$${values.length}`)}
  const clause=where.length?`WHERE ${where.join(' AND ')}`:'';const count=await pool.query(`SELECT COUNT(*)::int AS total FROM contacts ${clause}`,values);values.push(limit,offset);const r=await pool.query(`SELECT c.*,co.trade_name AS company_name FROM contacts c LEFT JOIN companies co ON co.id=c.company_id ${clause.replace(/company_id/g,'c.company_id').replace(/name ILIKE/g,'c.name ILIKE').replace(/email ILIKE/g,'c.email ILIKE').replace(/whatsapp ILIKE/g,'c.whatsapp ILIKE').replace(/role_type/g,'c.role_type').replace(/status/g,'c.status')} ORDER BY c.updated_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);res.json({data:{items:r.rows,pagination:{page,limit,total:count.rows[0].total}}});
}catch(e){next(e)}});

router.post('/contacts',async(req,res,next)=>{try{if(!canWrite(req))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});const name=cleanString(req.body?.name,180);if(!name)return res.status(400).json({error:'INVALID_INPUT',message:'Nome é obrigatório.'});const role=cleanString(req.body?.role_type,30);if(role&&!contactRoles.has(role))return res.status(400).json({error:'INVALID_INPUT',message:'Tipo de contato inválido.'});const status=cleanString(req.body?.status,30)||'ACTIVE';if(!contactStatuses.has(status))return res.status(400).json({error:'INVALID_INPUT',message:'Status de contato inválido.'});const companyId=uuid(req.body?.company_id)?req.body.company_id:null;if(companyId){const c=await pool.query('SELECT id FROM companies WHERE id=$1',[companyId]);if(!c.rowCount)return res.status(400).json({error:'INVALID_INPUT',message:'Empresa não encontrada.'})}const id=crypto.randomUUID();const r=await pool.query(`INSERT INTO contacts(id,company_id,name,job_title,email,phone,whatsapp,role_type,status,notes,owner_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[id,companyId,name,cleanString(req.body.job_title,120),cleanString(req.body.email,180),cleanString(req.body.phone,40),cleanString(req.body.whatsapp,40),role,status,cleanString(req.body.notes,5000),uuid(req.body.owner_id)?req.body.owner_id:req.user.id,req.user.id]);await audit(req,{action:'CREATE',entity:'contact',entityId:id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]});}catch(e){next(e)}});
router.get('/contacts/:id',async(req,res,next)=>{try{if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const r=await pool.query('SELECT c.*,co.trade_name AS company_name FROM contacts c LEFT JOIN companies co ON co.id=c.company_id WHERE c.id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND',message:'Contato não encontrado.'});res.json({data:r.rows[0]});}catch(e){next(e)}});
router.patch('/contacts/:id',async(req,res,next)=>{try{if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const current=(await pool.query('SELECT * FROM contacts WHERE id=$1',[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Contato não encontrado.'});if(!canWrite(req,current))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});const fields={name:['name',180],job_title:['job_title',120],email:['email',180],phone:['phone',40],whatsapp:['whatsapp',40],notes:['notes',5000],status:['status',30],role_type:['role_type',30]};const sets=[];const values=[];for(const [key,[col,max]] of Object.entries(fields)){if(req.body?.[key]!==undefined){const v=cleanString(req.body[key],max);if(key==='status'&&!contactStatuses.has(v))return res.status(400).json({error:'INVALID_INPUT',message:'Status de contato inválido.'});if(key==='role_type'&&v&&!contactRoles.has(v))return res.status(400).json({error:'INVALID_INPUT',message:'Tipo de contato inválido.'});sets.push(`${col}=$${values.length+1}`);values.push(v)}}if(req.body?.company_id!==undefined){const companyId=req.body.company_id===null?null:(uuid(req.body.company_id)?req.body.company_id:null);if(req.body.company_id!==null&&!companyId)return res.status(400).json({error:'INVALID_ID',message:'ID de empresa inválido.'});if(companyId&&!((await pool.query('SELECT id FROM companies WHERE id=$1',[companyId])).rowCount))return res.status(400).json({error:'INVALID_INPUT',message:'Empresa não encontrada.'});sets.push(`company_id=$${values.length+1}`);values.push(companyId)}if(uuid(req.body?.owner_id)){sets.push(`owner_id=$${values.length+1}`);values.push(req.body.owner_id)}if(!sets.length)return res.json({data:current});sets.push('updated_at=NOW()');values.push(req.params.id);const r=await pool.query(`UPDATE contacts SET ${sets.join(',')} WHERE id=$${values.length} RETURNING *`,values);await audit(req,{action:'UPDATE',entity:'contact',entityId:req.params.id,beforeData:current,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){next(e)}});
router.delete('/contacts/:id',async(req,res,next)=>{try{if(!canDelete(req))return res.status(403).json({error:'FORBIDDEN',message:'Somente administradores podem excluir contatos.'});if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const current=(await pool.query('SELECT * FROM contacts WHERE id=$1',[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Contato não encontrado.'});await pool.query('DELETE FROM contacts WHERE id=$1',[req.params.id]);await audit(req,{action:'DELETE',entity:'contact',entityId:req.params.id,beforeData:current});res.status(204).end();}catch(e){next(e)}});

router.get('/leads',async(req,res,next)=>{try{const {limit,page,offset}=parseLimitOffset(req);const values=[];const where=[];if(req.query.search){values.push(like(req.query.search));where.push(`(l.name ILIKE $${values.length} OR COALESCE(l.email,'') ILIKE $${values.length} OR COALESCE(l.whatsapp,'') ILIKE $${values.length} OR COALESCE(c.trade_name,'') ILIKE $${values.length})`)}if(leadStatuses.has(String(req.query.status||''))){values.push(req.query.status);where.push(`l.status=$${values.length}`)}if(uuid(req.query.source_id)){values.push(req.query.source_id);where.push(`l.source_id=$${values.length}`)}if(cleanString(req.query.product_interest,80)){values.push(req.query.product_interest);where.push(`l.product_interest=$${values.length}`)}if(cleanString(req.query.segment,100)){values.push(req.query.segment);where.push(`l.segment=$${values.length}`)}if(uuid(req.query.owner_id)){values.push(req.query.owner_id);where.push(`l.owner_id=$${values.length}`)}if(Number.isInteger(Number(req.query.score_min))){values.push(Number(req.query.score_min));where.push(`l.score >= $${values.length}`)}if(Number.isInteger(Number(req.query.score_max))){values.push(Number(req.query.score_max));where.push(`l.score <= $${values.length}`)}const clause=where.length?`WHERE ${where.join(' AND ')}`:'';const count=await pool.query(`SELECT COUNT(*)::int AS total FROM leads l LEFT JOIN companies c ON c.id=l.company_id ${clause}`,values);values.push(limit,offset);const r=await pool.query(`SELECT l.*,c.trade_name AS company_name,ct.name AS contact_name,ls.name AS source_name FROM leads l LEFT JOIN companies c ON c.id=l.company_id LEFT JOIN contacts ct ON ct.id=l.contact_id LEFT JOIN lead_sources ls ON ls.id=l.source_id ${clause} ORDER BY l.updated_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);res.json({data:{items:r.rows,pagination:{page,limit,total:count.rows[0].total}}});}catch(e){next(e)}});

router.post('/leads',async(req,res,next)=>{try{if(!canWrite(req))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});const name=cleanString(req.body?.name,180);if(!name)return res.status(400).json({error:'INVALID_INPUT',message:'Nome do lead é obrigatório.'});const score=req.body?.score==null?0:Number(req.body.score);if(!Number.isInteger(score)||score<0||score>100)return res.status(400).json({error:'INVALID_INPUT',message:'Score deve estar entre 0 e 100.'});const status=cleanString(req.body?.status,30)||'NEW';if(!leadStatuses.has(status))return res.status(400).json({error:'INVALID_INPUT',message:'Status de lead inválido.'});for(const field of ['company_id','contact_id','source_id'])if(req.body?.[field]!==undefined&&req.body[field]!==null&&!uuid(req.body[field]))return res.status(400).json({error:'INVALID_ID',message:`${field} inválido.`});const id=crypto.randomUUID();const r=await pool.query(`INSERT INTO leads(id,company_id,contact_id,source_id,name,email,phone,whatsapp,product_interest,segment,status,score,lost_reason,landing_page_url,utm_source,utm_medium,utm_campaign,utm_term,utm_content,notes,owner_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22) RETURNING *`,[id,req.body.company_id||null,req.body.contact_id||null,req.body.source_id||null,name,cleanString(req.body.email,180),cleanString(req.body.phone,40),cleanString(req.body.whatsapp,40),cleanString(req.body.product_interest,80),cleanString(req.body.segment,100),status,score,cleanString(req.body.lost_reason,180),cleanString(req.body.landing_page_url,1000),cleanString(req.body.utm_source,120),cleanString(req.body.utm_medium,120),cleanString(req.body.utm_campaign,180),cleanString(req.body.utm_term,180),cleanString(req.body.utm_content,180),cleanString(req.body.notes,5000),uuid(req.body.owner_id)?req.body.owner_id:req.user.id,req.user.id]);await pool.query('INSERT INTO lead_history(id,lead_id,event_type,to_status,description,created_by) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),id,'CREATED',status,'Lead criado',req.user.id]);await audit(req,{action:'CREATE',entity:'lead',entityId:id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]});}catch(e){next(e)}});
router.get('/leads/:id',async(req,res,next)=>{try{if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const r=await pool.query('SELECT l.*,c.trade_name AS company_name,ct.name AS contact_name,ls.name AS source_name FROM leads l LEFT JOIN companies c ON c.id=l.company_id LEFT JOIN contacts ct ON ct.id=l.contact_id LEFT JOIN lead_sources ls ON ls.id=l.source_id WHERE l.id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND',message:'Lead não encontrado.'});res.json({data:r.rows[0]});}catch(e){next(e)}});
router.get('/leads/:id/history',async(req,res,next)=>{try{if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const r=await pool.query('SELECT * FROM lead_history WHERE lead_id=$1 ORDER BY created_at DESC',[req.params.id]);res.json({data:r.rows});}catch(e){next(e)}});

router.patch('/leads/:id',async(req,res,next)=>{try{if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const current=(await pool.query('SELECT * FROM leads WHERE id=$1',[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Lead não encontrado.'});if(!canWrite(req,current))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});const fields={name:['name',180],email:['email',180],phone:['phone',40],whatsapp:['whatsapp',40],product_interest:['product_interest',80],segment:['segment',100],lost_reason:['lost_reason',180],landing_page_url:['landing_page_url',1000],utm_source:['utm_source',120],utm_medium:['utm_medium',120],utm_campaign:['utm_campaign',180],utm_term:['utm_term',180],utm_content:['utm_content',180],notes:['notes',5000]};const sets=[];const values=[];for(const [key,[col,max]] of Object.entries(fields)){if(req.body?.[key]!==undefined){sets.push(`${col}=$${values.length+1}`);values.push(cleanString(req.body[key],max))}}if(req.body?.score!==undefined){const score=Number(req.body.score);if(!Number.isInteger(score)||score<0||score>100)return res.status(400).json({error:'INVALID_INPUT',message:'Score deve estar entre 0 e 100.'});sets.push(`score=$${values.length+1}`);values.push(score)}for(const field of ['company_id','contact_id','source_id'])if(req.body?.[field]!==undefined){if(req.body[field]!==null&&!uuid(req.body[field]))return res.status(400).json({error:'INVALID_ID',message:`${field} inválido.`});sets.push(`${field}=$${values.length+1}`);values.push(req.body[field])}if(uuid(req.body?.owner_id)){sets.push(`owner_id=$${values.length+1}`);values.push(req.body.owner_id)}if(!sets.length)return res.json({data:current});sets.push('updated_at=NOW()');values.push(req.params.id);const r=await pool.query(`UPDATE leads SET ${sets.join(',')} WHERE id=$${values.length} RETURNING *`,values);await audit(req,{action:'UPDATE',entity:'lead',entityId:req.params.id,beforeData:current,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){next(e)}});

router.post('/leads/:id/status',async(req,res,next)=>{try{if(!uuid(req.params.id))return res.status(400).json({error:'INVALID_ID',message:'ID inválido.'});const current=(await pool.query('SELECT * FROM leads WHERE id=$1',[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Lead não encontrado.'});if(!canWrite(req,current))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});const nextStatus=cleanString(req.body?.status,30);if(!leadStatuses.has(nextStatus))return res.status(400).json({error:'INVALID_INPUT',message:'Status de lead inválido.'});if(nextStatus===current.status)return res.json({data:current});if(!allowedTransitions[current.status]?.has(nextStatus))return res.status(409).json({error:'INVALID_TRANSITION',message:`Transição ${current.status} → ${nextStatus} não permitida.`});const r=await pool.query('UPDATE leads SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[nextStatus,req.params.id]);await pool.query('INSERT INTO lead_history(id,lead_id,event_type,from_status,to_status,description,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[crypto.randomUUID(),req.params.id,'STATUS_CHANGED',current.status,nextStatus,`Status alterado de ${current.status} para ${nextStatus}`,req.user.id]);await audit(req,{action:'STATUS_CHANGE',entity:'lead',entityId:req.params.id,beforeData:current,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){next(e)}});
router.post('/leads/:id/qualify',async(req,res,next)=>{try{const score=req.body?.score==null?null:Number(req.body.score);const status=req.body?.status||'MQL';if(score!==null&&(!Number.isInteger(score)||score<0||score>100))return res.status(400).json({error:'INVALID_INPUT',message:'Score deve estar entre 0 e 100.'});if(!['MQL','SQL'].includes(status))return res.status(400).json({error:'INVALID_INPUT',message:'Qualificação aceita MQL ou SQL.'});const current=(await pool.query('SELECT * FROM leads WHERE id=$1',[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Lead não encontrado.'});if(!canWrite(req,current))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});if(!allowedTransitions[current.status]?.has(status))return res.status(409).json({error:'INVALID_TRANSITION',message:`Transição ${current.status} → ${status} não permitida.`});const r=await pool.query(`UPDATE leads SET status=$1,score=COALESCE($2,score),updated_at=NOW() WHERE id=$3 RETURNING *`,[status,score,req.params.id]);await pool.query('INSERT INTO lead_history(id,lead_id,event_type,from_status,to_status,description,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[crypto.randomUUID(),req.params.id,'QUALIFIED',current.status,status,`Lead qualificado como ${status}`,req.user.id]);await audit(req,{action:'QUALIFY',entity:'lead',entityId:req.params.id,beforeData:current,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){next(e)}});
router.post('/leads/:id/convert',async(req,res,next)=>{try{const current=(await pool.query('SELECT * FROM leads WHERE id=$1',[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Lead não encontrado.'});if(!canWrite(req,current))return res.status(403).json({error:'FORBIDDEN',message:'Permissão insuficiente.'});let company=null;let contact=null;if(current.company_id)company=(await pool.query('SELECT * FROM companies WHERE id=$1',[current.company_id])).rows[0];if(current.contact_id)contact=(await pool.query('SELECT * FROM contacts WHERE id=$1',[current.contact_id])).rows[0];if(!company&&req.body?.company){const name=cleanString(req.body.company.trade_name,180);if(name){const r=await pool.query(`INSERT INTO companies(id,trade_name,legal_name,phone,whatsapp,email,status,owner_id,created_by) VALUES($1,$2,$3,$4,$5,$6,'PROSPECT',$7,$8) RETURNING *`,[crypto.randomUUID(),name,cleanString(req.body.company.legal_name,220),cleanString(current.phone,40),cleanString(current.whatsapp,40),cleanString(current.email,180),req.user.id,req.user.id]);company=r.rows[0];await pool.query('UPDATE leads SET company_id=$1,updated_at=NOW() WHERE id=$2',[company.id,current.id])}}if(!contact&&req.body?.contact){const name=cleanString(req.body.contact.name,180)||current.name;const r=await pool.query(`INSERT INTO contacts(id,company_id,name,email,phone,whatsapp,status,owner_id,created_by) VALUES($1,$2,$3,$4,$5,$6,'ACTIVE',$7,$8) RETURNING *`,[crypto.randomUUID(),company?.id||null,name,cleanString(current.email,180),cleanString(current.phone,40),cleanString(current.whatsapp,40),req.user.id,req.user.id]);contact=r.rows[0];await pool.query('UPDATE leads SET contact_id=$1,updated_at=NOW() WHERE id=$2',[contact.id,current.id])}await pool.query('INSERT INTO lead_history(id,lead_id,event_type,description,metadata,created_by) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),current.id,'CONVERTED','Lead convertido em empresa/contato',JSON.stringify({companyId:company?.id||null,contactId:contact?.id||null}),req.user.id]);await audit(req,{action:'CONVERT',entity:'lead',entityId:current.id,afterData:{companyId:company?.id||null,contactId:contact?.id||null}});res.json({data:{lead:(await pool.query('SELECT * FROM leads WHERE id=$1',[current.id])).rows[0],company,contact}});}catch(e){next(e)}});

module.exports=router;
