const express=require('express');const crypto=require('crypto');const pool=require('../db/pool');const {requireAuth,requireRole}=require('../middleware/auth');const audit=require('../middleware/audit');const {text,uuid,oneOf}=require('../validators/common');
const {EXECUTION_TYPES,ensureTaskAcceptance,getTaskReadiness,normalizeType,inferExecutionType}=require('../services/task-acceptance');
const {createRequestFromWorkflow}=require('../services/approval-workflow');const router=express.Router();router.use(requireAuth);
const statuses=['BACKLOG','IN_PROGRESS','PENDING_APPROVAL','APPROVED','REJECTED','DONE','BLOCKED'];const priorities=['LOW','MEDIUM','HIGH','CRITICAL'];
const allowedTransitions={BACKLOG:['IN_PROGRESS','BLOCKED'],IN_PROGRESS:['PENDING_APPROVAL','BLOCKED','BACKLOG'],PENDING_APPROVAL:['APPROVED','REJECTED'],REJECTED:['IN_PROGRESS','BLOCKED'],APPROVED:['DONE'],BLOCKED:['IN_PROGRESS','BACKLOG'],DONE:['IN_PROGRESS']};
router.get('/',async(req,res,next)=>{try{const values=[];const filters=[];if(req.query.phase_id){values.push(uuid(req.query.phase_id));filters.push(`t.phase_id=$${values.length}`)}if(req.query.status){values.push(oneOf(req.query.status,statuses));filters.push(`t.status=$${values.length}`)}const r=await pool.query(`SELECT t.*,p.name phase_name,p.color phase_color,a.name assignee_name,r.name reviewer_name,COALESCE((SELECT SUM(hours) FROM task_time_entries te WHERE te.task_id=t.id),0)::numeric worked_hours,COALESCE((SELECT COUNT(*) FROM task_subtasks s WHERE s.task_id=t.id),0)::int subtask_count,COALESCE((SELECT COUNT(*) FROM task_subtasks s WHERE s.task_id=t.id AND s.is_done),0)::int subtask_done_count FROM tasks t JOIN phases p ON p.id=t.phase_id LEFT JOIN users a ON a.id=t.assignee_id LEFT JOIN users r ON r.id=t.reviewer_id ${filters.length?'WHERE '+filters.join(' AND '):''} ORDER BY t.due_date NULLS LAST,t.created_at DESC`,values);res.json({data:r.rows});}catch(e){next(e)}});
router.post('/',requireRole('ADMIN'),async(req,res,next)=>{const client=await pool.connect();try{await client.query('BEGIN');const title=text(req.body.title,220);const executionType=normalizeType(req.body.execution_type||inferExecutionType(title));const r=await client.query('INSERT INTO tasks(id,phase_id,title,description,status,priority,assignee_id,reviewer_id,due_date,created_by,execution_type) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[crypto.randomUUID(),uuid(req.body.phase_id),title,req.body.description||null,'BACKLOG',oneOf(req.body.priority||'MEDIUM',priorities),req.body.assignee_id?uuid(req.body.assignee_id):null,req.body.reviewer_id?uuid(req.body.reviewer_id):null,req.body.due_date||null,req.user.id,executionType]);await ensureTaskAcceptance(client,r.rows[0].id,executionType);await client.query('COMMIT');await audit(req,{action:'CREATE',entity:'task',entityId:r.rows[0].id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]});}catch(e){await client.query('ROLLBACK').catch(()=>{});next(e)}finally{client.release()}});
async function getTask(taskId){const r=await pool.query('SELECT * FROM tasks WHERE id=$1',[taskId]);return r.rows[0];}
function canOperateTask(user,task){return user.role==='ADMIN'||user.role==='MANAGER'||task.assignee_id===user.id;}
function canCommentTask(user,task){return canOperateTask(user,task)||user.role==='STAKEHOLDER';}
router.patch('/:id',async(req,res,next)=>{try{const taskId=uuid(req.params.id);const before=await getTask(taskId);if(!before)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(req.user.role!=='ADMIN'&&req.user.role!=='MANAGER'&&before.assignee_id!==req.user.id)return res.status(403).json({error:'FORBIDDEN',message:'Somente o responsável, gestor ou administrador pode editar esta tarefa.'});
if(req.body.status!==undefined){const nextStatus=oneOf(req.body.status,statuses);if(nextStatus!==before.status){if(req.user.role!=='ADMIN'&&before.assignee_id!==req.user.id)return res.status(403).json({error:'FORBIDDEN',message:'Somente o responsável ou ADMIN pode alterar o status.'});if(req.user.role!=='ADMIN'&&!allowedTransitions[before.status]?.includes(nextStatus))return res.status(409).json({error:'INVALID_TRANSITION',message:`Transição ${before.status} → ${nextStatus} não permitida.`});if(nextStatus==='PENDING_APPROVAL'){const readiness=await getTaskReadiness(pool,taskId);if(!readiness?.ready)return res.status(409).json({error:'TASK_NOT_READY_FOR_APPROVAL',message:'A tarefa ainda não atende aos critérios mínimos de aprovação.',details:{criteria:readiness?.criteria?.missing||[],evidence:readiness?.evidence?.missing||[],deliverable:readiness?.deliverable?.ready}});if(req.user.role!=='ADMIN')return res.status(403).json({error:'FORBIDDEN',message:'Use o envio para aprovação.'});}if(nextStatus==='BLOCKED'&&!String(req.body.blocked_reason||before.blocked_reason||'').trim())return res.status(400).json({error:'BLOCK_REASON_REQUIRED',message:'Informe o motivo do bloqueio.'});await pool.query('INSERT INTO task_status_history(id,task_id,changed_by,from_status,to_status,note) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),taskId,req.user.id,before.status,nextStatus,req.body.note?text(req.body.note,2000):null]);}}
const allowed=['title','description','priority','assignee_id','reviewer_id','due_date','status','estimated_hours','blocked_reason','position'];const sets=[],values=[];for(const key of allowed){if(req.body[key]!==undefined){let value=req.body[key]===''?null:req.body[key];if(key==='title')value=text(value,220);if(key==='priority')value=oneOf(value,priorities);if(key==='status')value=oneOf(value,statuses);if(['assignee_id','reviewer_id'].includes(key)&&value)value=uuid(value);if(['estimated_hours','position'].includes(key)&&value!==null)value=Number(value);if(key==='blocked_reason'&&value)value=text(value,1000);sets.push(`${key}=$${values.length+1}`);values.push(value);}}
if(!sets.length)return res.status(400).json({error:'NO_CHANGES',message:'Nada para atualizar.'});values.push(taskId);const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`UPDATE tasks SET ${sets.join(',')},updated_at=NOW() WHERE id=$${values.length} RETURNING *`,values);await client.query('COMMIT');await audit(req,{action:req.body.status&&req.body.status!==before.status?'STATUS_CHANGE':'UPDATE',entity:'task',entityId:taskId,beforeData:before,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){await client.query('ROLLBACK').catch(()=>{});next(e)}finally{client.release()}}catch(e){next(e)}});
router.post('/:id/submit',async(req,res,next)=>{const taskId=uuid(req.params.id);const client=await pool.connect();try{await client.query('BEGIN');const before=(await client.query('SELECT * FROM tasks WHERE id=$1 FOR UPDATE',[taskId])).rows[0];if(!before)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(req.user.role!=='ADMIN'&&before.assignee_id!==req.user.id)return res.status(403).json({error:'FORBIDDEN',message:'Somente o responsável pode enviar para aprovação.'});if(!['IN_PROGRESS','REJECTED'].includes(before.status))return res.status(409).json({error:'INVALID_STATE',message:'A tarefa não pode ser enviada para aprovação neste estado.'});const readiness=await getTaskReadiness(client,taskId);if(!readiness?.ready)return res.status(409).json({error:'TASK_NOT_READY_FOR_APPROVAL',message:'A tarefa ainda não atende aos critérios mínimos de aprovação.',details:{criteria:readiness?.criteria?.missing||[],evidence:readiness?.evidence?.missing||[],deliverable:readiness?.deliverable?.ready}});const open=await client.query("SELECT id FROM approval_requests WHERE entity='task' AND entity_id=$1 AND status='PENDING' FOR UPDATE",[taskId]);if(open.rowCount)return res.status(409).json({error:'APPROVAL_ALREADY_OPEN',message:'Já existe uma aprovação pendente para esta tarefa.'});const created=await createRequestFromWorkflow(client,{entity:'task',entityId:taskId,workflowType:'TASK',requestedBy:req.user.id,legacyReviewerId:before.reviewer_id});const r=await client.query("UPDATE tasks SET status='PENDING_APPROVAL',updated_at=NOW() WHERE id=$1 RETURNING *",[taskId]);await client.query('INSERT INTO task_status_history(id,task_id,changed_by,from_status,to_status,note) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),taskId,req.user.id,before.status,'PENDING_APPROVAL','Enviada para aprovação']);await client.query('COMMIT');await audit(req,{action:'SUBMIT_APPROVAL',entity:'task',entityId:taskId,beforeData:before,afterData:{status:r.rows[0].status,approval_request_id:created.requestId,workflow:created.workflow?.name}});res.status(201).json({data:{task:r.rows[0],request_id:created.requestId}});}catch(e){await client.query('ROLLBACK').catch(()=>{});next(e)}finally{client.release()}});

router.post('/:id/approve',requireRole('ADMIN','STAKEHOLDER'),async(req,res,next)=>{try{const taskId=uuid(req.params.id);const before=await getTask(taskId);if(!before)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(before.status!=='PENDING_APPROVAL'||(before.reviewer_id&&before.reviewer_id!==req.user.id&&req.user.role!=='ADMIN'))return res.status(409).json({error:'INVALID_APPROVAL',message:'Tarefa não está aguardando sua aprovação.'});const note=req.body.note?text(req.body.note,2000):'Aprovada.';const r=await pool.query("UPDATE tasks SET status='APPROVED',approval_note=$1,deliverable_status=CASE WHEN deliverable_status='SUBMITTED' THEN 'APPROVED' ELSE deliverable_status END,updated_at=NOW() WHERE id=$2 RETURNING *",[note,taskId]);await pool.query('INSERT INTO task_status_history(id,task_id,changed_by,from_status,to_status,note) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),taskId,req.user.id,before.status,'APPROVED',note]);await audit(req,{action:'APPROVE',entity:'task',entityId:taskId,beforeData:before,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){next(e)}});
router.post('/:id/reject',requireRole('ADMIN','STAKEHOLDER'),async(req,res,next)=>{try{const taskId=uuid(req.params.id);const before=await getTask(taskId);if(!before)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(before.status!=='PENDING_APPROVAL'||(before.reviewer_id&&before.reviewer_id!==req.user.id&&req.user.role!=='ADMIN'))return res.status(409).json({error:'INVALID_APPROVAL',message:'Tarefa não está aguardando sua aprovação.'});const note=text(req.body.note,2000);const r=await pool.query("UPDATE tasks SET status='REJECTED',rejection_note=$1,deliverable_status=CASE WHEN deliverable_status='SUBMITTED' THEN 'REJECTED' ELSE deliverable_status END,updated_at=NOW() WHERE id=$2 RETURNING *",[note,taskId]);await pool.query('INSERT INTO task_status_history(id,task_id,changed_by,from_status,to_status,note) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),taskId,req.user.id,before.status,'REJECTED',note]);await audit(req,{action:'REJECT',entity:'task',entityId:taskId,beforeData:before,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){next(e)}});
router.get('/:id/readiness',async(req,res,next)=>{try{const taskId=uuid(req.params.id);const task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});const readiness=await getTaskReadiness(pool,taskId);res.json({data:readiness});}catch(e){next(e)}});
router.post('/:id/acceptance-criteria',async(req,res,next)=>{try{const taskId=uuid(req.params.id),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para configurar critérios de aceite.'});const title=text(req.body.title,220);if(!title)return res.status(400).json({error:'INVALID_INPUT',message:'Título do critério é obrigatório.'});const description=req.body.description?text(req.body.description,2000):null;const required=req.body.required!==false;const r=await pool.query('INSERT INTO task_acceptance_criteria(id,task_id,title,description,required,position) VALUES($1,$2,$3,$4,$5,COALESCE((SELECT MAX(position)+1 FROM task_acceptance_criteria WHERE task_id=$2),0)) RETURNING *',[crypto.randomUUID(),taskId,title,description,required]);await audit(req,{action:'CREATE',entity:'task_acceptance_criterion',entityId:r.rows[0].id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]});}catch(e){next(e)}});
router.patch('/:id/acceptance-criteria/:criterionId',async(req,res,next)=>{try{const taskId=uuid(req.params.id),criterionId=uuid(req.params.criterionId),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para atualizar critérios de aceite.'});const current=(await pool.query('SELECT * FROM task_acceptance_criteria WHERE id=$1 AND task_id=$2',[criterionId,taskId])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Critério de aceite não encontrado.'});if(current.system_key)return res.status(409).json({error:'SYSTEM_CRITERION',message:'Este critério é calculado automaticamente.'});const isComplete=req.body.is_complete!==undefined?Boolean(req.body.is_complete):current.is_complete;const title=req.body.title!==undefined?text(req.body.title,220):current.title;const description=req.body.description!==undefined?(req.body.description?text(req.body.description,2000):null):current.description;const required=req.body.required!==undefined?Boolean(req.body.required):current.required;const r=await pool.query('UPDATE task_acceptance_criteria SET title=$1,description=$2,required=$3,is_complete=$4,completed_by=$5,completed_at=CASE WHEN $4 THEN NOW() ELSE NULL END,updated_at=NOW() WHERE id=$6 RETURNING *',[title,description,required,isComplete,isComplete?req.user.id:null,criterionId]);await audit(req,{action:'UPDATE',entity:'task_acceptance_criterion',entityId:criterionId,beforeData:current,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){next(e)}});
router.delete('/:id/acceptance-criteria/:criterionId',async(req,res,next)=>{try{const taskId=uuid(req.params.id),criterionId=uuid(req.params.criterionId),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(req.user.role!=='ADMIN')return res.status(403).json({error:'FORBIDDEN',message:'Somente ADMIN pode excluir critérios de aceite.'});const r=await pool.query('DELETE FROM task_acceptance_criteria WHERE id=$1 AND task_id=$2 RETURNING *',[criterionId,taskId]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND',message:'Critério de aceite não encontrado.'});await audit(req,{action:'DELETE',entity:'task_acceptance_criterion',entityId:criterionId,beforeData:r.rows[0]});res.status(204).end();}catch(e){next(e)}});

router.get('/:id/details', async (req, res, next) => {
  try {
    const taskId = uuid(req.params.id);
    const task = await pool.query(`SELECT t.*,p.name phase_name,p.short_name phase_short_name,p.start_date phase_start_date,p.end_date phase_end_date,p.objective phase_objective,p.color phase_color,c.name campaign_name,a.name assignee_name,r.name reviewer_name,creator.name created_by_name,submitter.name deliverable_submitted_by_name,(SELECT ar.id FROM approval_requests ar WHERE ar.entity='task' AND ar.entity_id=t.id AND ar.status='PENDING' ORDER BY ar.requested_at DESC LIMIT 1) approval_request_id,(SELECT ar.status FROM approval_requests ar WHERE ar.entity='task' AND ar.entity_id=t.id AND ar.status='PENDING' ORDER BY ar.requested_at DESC LIMIT 1) approval_request_status,COALESCE((SELECT SUM(hours) FROM task_time_entries te WHERE te.task_id=t.id),0)::numeric worked_hours,COALESCE((SELECT COUNT(*) FROM task_subtasks s WHERE s.task_id=t.id),0)::int subtask_count,COALESCE((SELECT COUNT(*) FROM task_subtasks s WHERE s.task_id=t.id AND s.is_done),0)::int subtask_done_count FROM tasks t JOIN phases p ON p.id=t.phase_id JOIN campaigns c ON c.id=p.campaign_id LEFT JOIN users a ON a.id=t.assignee_id LEFT JOIN users r ON r.id=t.reviewer_id LEFT JOIN users creator ON creator.id=t.created_by LEFT JOIN users submitter ON submitter.id=t.deliverable_submitted_by WHERE t.id=$1`, [taskId]);
    if (!task.rowCount) return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});
    const [subtasks, history, comments, time, evidence, acceptanceCriteria, readiness] = await Promise.all([
      pool.query('SELECT s.*,u.name created_by_name FROM task_subtasks s LEFT JOIN users u ON u.id=s.created_by WHERE s.task_id=$1 ORDER BY s.position,s.created_at',[taskId]),
      pool.query('SELECT h.*,u.name changed_by_name FROM task_status_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.task_id=$1 ORDER BY h.created_at DESC',[taskId]),
      pool.query('SELECT c.*,u.name author_name FROM task_comments c LEFT JOIN users u ON u.id=c.user_id WHERE c.task_id=$1 ORDER BY c.created_at DESC',[taskId]),
      pool.query('SELECT te.*,u.name user_name FROM task_time_entries te LEFT JOIN users u ON u.id=te.user_id WHERE te.task_id=$1 ORDER BY te.logged_at DESC',[taskId]),
      pool.query('SELECT e.*,u.name user_name FROM task_evidence e LEFT JOIN users u ON u.id=e.user_id WHERE e.task_id=$1 ORDER BY e.created_at DESC',[taskId]),
      pool.query('SELECT c.*,u.name completed_by_name FROM task_acceptance_criteria c LEFT JOIN users u ON u.id=c.completed_by WHERE c.task_id=$1 ORDER BY c.position,c.created_at',[taskId]),
      getTaskReadiness(pool, taskId)
    ]);
    res.json({data:{task:task.rows[0],subtasks:subtasks.rows,history:history.rows,comments:comments.rows,timeEntries:time.rows,evidence:evidence.rows,acceptanceCriteria:acceptanceCriteria.rows,readiness}});
  } catch (e) {
    if (['42P01','42703'].includes(e.code)) {
      console.error(`[TASK_DETAILS_SCHEMA] ${req.id} ${e.code}: ${e.message}`);
      return res.status(503).json({error:'DB_MIGRATION_REQUIRED',message:'A estrutura de execução e aprovação do banco está incompleta. Execute npm run db:migrate e tente novamente.',requiredMigration:'017_execution_schema_reconciliation',requestId:req.id});
    }
    next(e);
  }
});

router.post('/:id/subtasks',async(req,res,next)=>{try{const taskId=uuid(req.params.id),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para adicionar microtarefas.'});const title=text(req.body.title,220);const r=await pool.query('INSERT INTO task_subtasks(id,task_id,title,position,created_by) VALUES($1,$2,$3,COALESCE((SELECT MAX(position)+1 FROM task_subtasks WHERE task_id=$2),0),$4) RETURNING *',[crypto.randomUUID(),taskId,title,req.user.id]);await audit(req,{action:'CREATE',entity:'task_subtask',entityId:r.rows[0].id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]});}catch(e){next(e)}});

router.patch('/:id/subtasks/:subtaskId',async(req,res,next)=>{try{const taskId=uuid(req.params.id),subtaskId=uuid(req.params.subtaskId);const task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para editar esta microtarefa.'});const current=(await pool.query('SELECT * FROM task_subtasks WHERE id=$1 AND task_id=$2',[subtaskId,taskId])).rows[0];if(!current)return res.status(404).json({error:'NOT_FOUND',message:'Microtarefa não encontrada.'});const title=req.body.title!==undefined?text(req.body.title,220):current.title;if(!title)return res.status(400).json({error:'INVALID_INPUT',message:'Título da microtarefa é obrigatório.'});const isDone=req.body.is_done!==undefined?Boolean(req.body.is_done):current.is_done;const position=req.body.position!==undefined?Number(req.body.position):current.position;const r=await pool.query('UPDATE task_subtasks SET title=$1,is_done=$2,position=$3,updated_at=NOW() WHERE id=$4 AND task_id=$5 RETURNING *',[title,isDone,position,subtaskId,taskId]);await audit(req,{action:'UPDATE',entity:'task_subtask',entityId:subtaskId,beforeData:current,afterData:r.rows[0]});res.json({data:r.rows[0]})}catch(e){next(e)}});
router.delete('/:id/subtasks/:subtaskId',async(req,res,next)=>{try{const taskId=uuid(req.params.id),subtaskId=uuid(req.params.subtaskId);const task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para excluir esta microtarefa.'});const r=await pool.query('DELETE FROM task_subtasks WHERE id=$1 AND task_id=$2 RETURNING *',[subtaskId,taskId]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND',message:'Microtarefa não encontrada.'});await audit(req,{action:'DELETE',entity:'task_subtask',entityId:subtaskId,beforeData:r.rows[0]});res.status(204).end()}catch(e){next(e)}});

router.post('/:id/comments',async(req,res,next)=>{try{const taskId=uuid(req.params.id),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canCommentTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para comentar nesta tarefa.'});const body=text(req.body.body,4000);const r=await pool.query('INSERT INTO task_comments(id,task_id,user_id,body) VALUES($1,$2,$3,$4) RETURNING *',[crypto.randomUUID(),taskId,req.user.id,body]);await audit(req,{action:'CREATE',entity:'task_comment',entityId:r.rows[0].id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]});}catch(e){next(e)}});

router.post('/:id/time',async(req,res,next)=>{try{const taskId=uuid(req.params.id),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para registrar horas nesta tarefa.'});const hours=Number(req.body.hours);if(!Number.isFinite(hours)||hours<=0||hours>24)return res.status(400).json({error:'INVALID_HOURS',message:'Informe entre 0,01 e 24 horas.'});const note=req.body.note?text(req.body.note,500):null;const r=await pool.query('INSERT INTO task_time_entries(id,task_id,user_id,hours,note) VALUES($1,$2,$3,$4,$5) RETURNING *',[crypto.randomUUID(),taskId,req.user.id,hours,note]);await audit(req,{action:'CREATE',entity:'task_time_entry',entityId:r.rows[0].id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]});}catch(e){next(e)}});

router.post('/:id/evidence',async(req,res,next)=>{try{const taskId=uuid(req.params.id),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para registrar evidências nesta tarefa.'});const title=text(req.body.title,220);const type=oneOf(req.body.evidence_type||'LINK',['LINK','NOTE','IMAGE','DOCUMENT']);const url=req.body.url?text(req.body.url,2000):null;const description=req.body.description?text(req.body.description,4000):null;if(type==='LINK'&&!url)return res.status(400).json({error:'URL_REQUIRED',message:'Informe a URL da evidência.'});const r=await pool.query('INSERT INTO task_evidence(id,task_id,user_id,evidence_type,title,url,description) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[crypto.randomUUID(),taskId,req.user.id,type,title,url,description]);await audit(req,{action:'CREATE',entity:'task_evidence',entityId:r.rows[0].id,afterData:r.rows[0]});res.status(201).json({data:r.rows[0]});}catch(e){next(e)}});

router.delete('/:id/evidence/:evidenceId',async(req,res,next)=>{try{const taskId=uuid(req.params.id),evidenceId=uuid(req.params.evidenceId),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para remover evidências desta tarefa.'});const r=await pool.query('DELETE FROM task_evidence WHERE id=$1 AND task_id=$2 RETURNING *',[evidenceId,taskId]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND',message:'Evidência não encontrada.'});await audit(req,{action:'DELETE',entity:'task_evidence',entityId:evidenceId,beforeData:r.rows[0]});res.status(204).end();}catch(e){next(e)}});

router.patch('/:id/deliverable',async(req,res,next)=>{try{const taskId=uuid(req.params.id),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para editar o entregável desta tarefa.'});const deliverable=text(req.body.deliverable,10000);const status=oneOf(req.body.status||task.deliverable_status||'DRAFT',['DRAFT','SUBMITTED']);const r=await pool.query(`UPDATE tasks SET deliverable=$1,deliverable_status=$2,deliverable_submitted_at=CASE WHEN $2='SUBMITTED' THEN NOW() WHEN $2='DRAFT' THEN NULL ELSE deliverable_submitted_at END,deliverable_submitted_by=CASE WHEN $2='SUBMITTED' THEN $3 WHEN $2='DRAFT' THEN NULL ELSE deliverable_submitted_by END,updated_at=NOW() WHERE id=$4 RETURNING *`,[deliverable,status,req.user.id,taskId]);await audit(req,{action:'UPDATE',entity:'task_deliverable',entityId:taskId,beforeData:{deliverable:task.deliverable,deliverable_status:task.deliverable_status},afterData:{deliverable:r.rows[0].deliverable,deliverable_status:r.rows[0].deliverable_status}});res.json({data:r.rows[0]});}catch(e){next(e)}});

router.post('/:id/block',async(req,res,next)=>{try{const taskId=uuid(req.params.id),task=await getTask(taskId);if(!task)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});if(!canOperateTask(req.user,task))return res.status(403).json({error:'FORBIDDEN',message:'Sem permissão para bloquear esta tarefa.'});const reason=text(req.body.reason,1000);if(!reason)return res.status(400).json({error:'BLOCK_REASON_REQUIRED',message:'Informe o motivo do bloqueio.'});const r=await pool.query("UPDATE tasks SET status='BLOCKED',blocked_reason=$1,updated_at=NOW() WHERE id=$2 RETURNING *",[reason,taskId]);await pool.query('INSERT INTO task_status_history(id,task_id,changed_by,from_status,to_status,note) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),taskId,req.user.id,task.status,'BLOCKED',reason]);await audit(req,{action:'STATUS_CHANGE',entity:'task',entityId:taskId,beforeData:task,afterData:r.rows[0]});res.json({data:r.rows[0]});}catch(e){next(e)}});

router.get('/:id/history',async(req,res,next)=>{try{const taskId=uuid(req.params.id);const r=await pool.query('SELECT h.*,u.name changed_by_name FROM task_status_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.task_id=$1 ORDER BY h.created_at DESC',[taskId]);res.json({data:r.rows});}catch(e){next(e)}});
router.delete('/:id',requireRole('ADMIN'),async(req,res,next)=>{try{const taskId=uuid(req.params.id);const before=await getTask(taskId);if(!before)return res.status(404).json({error:'NOT_FOUND',message:'Tarefa não encontrada.'});await pool.query('DELETE FROM tasks WHERE id=$1',[taskId]);await audit(req,{action:'DELETE',entity:'task',entityId:taskId,beforeData:before});res.status(204).end();}catch(e){next(e)}});
module.exports=router;
