-- G3Soft Growth OS v1.0.2 — Task Execution & Deliverables
-- Additive/idempotent. Adds execution guidance and acceptance deliverables to roadmap tasks.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS execution_plan TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS deliverable TEXT;
CREATE INDEX IF NOT EXISTS idx_tasks_execution ON tasks(phase_id, status, due_date);

WITH specs(title, execution_plan, deliverable) AS (
  VALUES
    ('Auditoria completa do site, SEO, anúncios e CRM', 'Executar de forma sequencial e documentada: Mapear site, páginas, formulários e conversões atuais; Auditar SEO técnico, on-page e indexação; Inventariar campanhas, anúncios, públicos e investimentos; Auditar CRM, fontes de leads e integrações existentes; Consolidar gaps, riscos e prioridades em diagnóstico executivo. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Diagnóstico executivo de Growth com inventário de ativos, gaps priorizados, riscos, evidências e backlog de correções.'),
    ('Definição de ICP e personas', 'Executar de forma sequencial e documentada: Definir segmentos prioritários e critérios de fit; Mapear decisores, influenciadores e usuários; Documentar dores, necessidades, objeções e gatilhos; Definir sinais de intenção e critérios de qualificação; Validar ICP e personas com stakeholders. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Documento validado de ICP e personas, com critérios de fit, decisores, dores, objeções e sinais de intenção.'),
    ('Estratégia de posicionamento e mensagens', 'Executar de forma sequencial e documentada: Definir proposta de valor principal; Definir diferenciais competitivos e provas; Criar mensagens por ICP e estágio do funil; Definir argumentos para site, anúncios e vendas; Documentar guia de mensagens e tom comercial. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Guia de posicionamento e mensagens por ICP e estágio do funil, pronto para uso em site, mídia e vendas.'),
    ('Estruturação de analytics e dashboard', 'Executar de forma sequencial e documentada: Mapear funil de aquisição até receita; Definir eventos e conversões prioritárias; Definir nomenclatura e UTMs; Mapear KPIs, dimensões e fontes de dados; Validar dashboard executivo e rotina de leitura. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Plano de mensuração e dashboard executivo com eventos, UTMs, KPIs, fontes e rotina de leitura.'),
    ('Implementação do CRM e integrações', 'Executar de forma sequencial e documentada: Definir campos e etapas comerciais; Padronizar cadastro de empresas, contatos e leads; Configurar fontes e origem dos leads; Mapear integrações e responsabilidades; Executar teste ponta a ponta do fluxo comercial. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'CRM configurado com campos, etapas, origens, responsabilidades e fluxo ponta a ponta validado.'),
    ('Plano de conteúdo e calendário editorial', 'Executar de forma sequencial e documentada: Definir pilares editoriais; Mapear temas por ICP e intenção; Criar matriz de formatos e canais; Planejar calendário dos primeiros 30 dias; Definir fluxo de produção, revisão e aprovação. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Calendário editorial inicial com pilares, temas, formatos, canais, responsáveis e fluxo de aprovação.'),
    ('Criação das primeiras landing pages', 'Executar de forma sequencial e documentada: Definir oferta e objetivo de cada landing page; Criar estrutura de headline, benefícios e prova; Implementar formulário e CTA principal; Configurar tracking de conversão; Publicar e validar experiência mobile. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Landing pages publicadas, responsivas e rastreadas, com oferta, prova, formulário e CTA validados.'),
    ('Otimização de formulários e CTAs', 'Executar de forma sequencial e documentada: Mapear formulários atuais e pontos de abandono; Reduzir campos sem comprometer qualificação; Padronizar microcopy e estados de erro; Criar CTAs por intenção e estágio; Instrumentar eventos de clique e envio. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Formulários e CTAs otimizados, instrumentados e validados com redução de fricção e critérios de qualificação.'),
    ('Implementação de WhatsApp integrado ao CRM', 'Executar de forma sequencial e documentada: Definir pontos de entrada para WhatsApp; Mapear identificação do lead e origem; Registrar conversas e oportunidades no CRM; Criar handoff entre marketing e comercial; Testar fluxo completo de entrada até follow-up. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Fluxo WhatsApp + CRM operacional, com origem identificada, handoff comercial e teste ponta a ponta concluído.'),
    ('Fluxos de nutrição iniciais por e-mail e WhatsApp', 'Executar de forma sequencial e documentada: Definir segmentos de nutrição; Criar sequência de boas-vindas; Criar sequência de educação e prova; Criar gatilho de intenção para vendas; Mensurar abertura, resposta, clique e avanço. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Fluxo WhatsApp + CRM operacional, com origem identificada, handoff comercial e teste ponta a ponta concluído.'),
    ('Campanhas Google Ads de alta intenção', 'Executar de forma sequencial e documentada: Mapear palavras-chave de alta intenção; Criar grupos e mensagens por intenção; Configurar conversões e UTMs; Publicar campanhas e validar tracking; Criar rotina de otimização de termos e anúncios. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Campanhas Google Ads configuradas/publicadas com estrutura por intenção, conversões, UTMs e rotina de otimização.'),
    ('A/B tests e otimizações contínuas', 'Executar de forma sequencial e documentada: Selecionar hipóteses de maior impacto; Definir métrica primária e janela do teste; Criar variações de páginas e CTAs; Executar teste controlado; Registrar resultado e decidir próxima iteração. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Relatório de experimentos com hipóteses, métricas, variações, resultados e decisão da próxima iteração.'),
    ('Escala de campanhas Google Ads', 'Executar de forma sequencial e documentada: Identificar campanhas e grupos vencedores; Redistribuir orçamento para intenção comprovada; Expandir palavras e variações vencedoras; Ajustar lances e negativos; Monitorar CAC, CPL e qualidade dos leads. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Campanhas Google Ads configuradas/publicadas com estrutura por intenção, conversões, UTMs e rotina de otimização.'),
    ('Campanhas Meta Ads', 'Executar de forma sequencial e documentada: Definir públicos por estágio do funil; Criar criativos de descoberta e dor; Criar anúncios de prova e conversão; Configurar eventos e UTMs; Rodar ciclos de teste e otimização. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Estrutura de Meta Ads ativa com públicos, criativos, eventos, UTMs e ciclos de teste documentados.'),
    ('SEO on-page e conteúdo estratégico', 'Executar de forma sequencial e documentada: Priorizar páginas e palavras-chave; Corrigir títulos, headings e links internos; Criar clusters de conteúdo; Publicar conteúdos orientados à intenção; Monitorar indexação e evolução orgânica. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Plano/implementação de SEO com páginas prioritárias, correções on-page/técnicas, conteúdos e backlog contínuo.'),
    ('YouTube: vídeos e cases', 'Executar de forma sequencial e documentada: Definir pautas de vídeos por intenção; Roteirizar vídeos de demonstração; Produzir cases e provas; Publicar com SEO e CTA; Conectar vídeos ao funil e às landing pages. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Pacote de vídeos/cases publicado com SEO, CTA e conexão mensurável com o funil e landing pages.'),
    ('Retargeting avançado e públicos semelhantes', 'Executar de forma sequencial e documentada: Mapear públicos de visitantes e engajados; Criar janelas de retargeting; Criar públicos semelhantes quando houver volume; Criar mensagens por estágio de consciência; Medir incrementalidade e frequência. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Estrutura de remarketing e públicos semelhantes configurada, segmentada por estágio e com medição de incrementalidade.'),
    ('Otimização de campanhas e segmentações', 'Executar de forma sequencial e documentada: Comparar performance por campanha, público e canal; Identificar desperdícios e gargalos; Revisar segmentações e exclusões; Realocar orçamento para eficiência; Documentar decisões e hipóteses. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Relatório de otimização com desperdícios, gargalos, ajustes de segmentação, orçamento e hipóteses registradas.'),
    ('Lead scoring e qualificação automática', 'Executar de forma sequencial e documentada: Definir atributos firmográficos e comportamentais; Criar matriz de pontuação; Definir MQL e SQL; Automatizar mudança de estágio; Validar qualidade dos leads com vendas. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Modelo de lead scoring e qualificação automática implementado, com critérios MQL/SQL e validação junto a vendas.'),
    ('Análise de CAC, CPL, ROAS e conversões', 'Executar de forma sequencial e documentada: Consolidar investimento por canal; Calcular CPL e CAC por período; Calcular ROAS por campanha; Mapear conversões por etapa; Criar rotina executiva de análise. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Relatório executivo de eficiência com CAC, CPL, ROAS e conversões por canal/período, incluindo decisões recomendadas.'),
    ('Ajustes em funis e ofertas', 'Executar de forma sequencial e documentada: Identificar maior queda do funil; Revisar oferta e proposta de valor; Testar prova, garantia e CTA; Otimizar handoffs marketing-vendas; Medir impacto sobre conversão. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Funil e oferta revisados, com gargalos priorizados, testes de proposta/CTA e impacto de conversão medido.'),
    ('Dashboards avançados e relatórios executivos', 'Executar de forma sequencial e documentada: Definir painéis por função; Criar visão executiva semanal; Criar visão comercial do funil; Criar visão de mídia e conteúdo; Padronizar relatório e reunião de performance. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Plano de mensuração e dashboard executivo com eventos, UTMs, KPIs, fontes e rotina de leitura.'),
    ('Otimização de conteúdo e SEO técnico', 'Executar de forma sequencial e documentada: Auditar conteúdos com baixa performance; Atualizar conteúdos prioritários; Corrigir links e estrutura técnica; Melhorar Core Web Vitals quando aplicável; Criar backlog contínuo de SEO. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Plano/implementação de SEO com páginas prioritárias, correções on-page/técnicas, conteúdos e backlog contínuo.'),
    ('Fluxos de automação avançados', 'Executar de forma sequencial e documentada: Mapear gatilhos de alto volume; Definir condições e ações; Automatizar distribuição de tarefas; Automatizar follow-ups e alertas; Monitorar falhas e exceções. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Fluxos de automação configurados, testados e monitorados, com gatilhos, condições, ações e tratamento de exceções.'),
    ('Sequências de nutrição inteligente', 'Executar de forma sequencial e documentada: Segmentar por intenção e comportamento; Criar sequências por estágio; Definir gatilhos de avanço; Criar regras de pausa e saída; Medir avanço para oportunidade. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Sequências de nutrição publicadas e mensuradas, com segmentos, gatilhos, critérios de saída e passagem para vendas.'),
    ('Recuperação de leads perdidos', 'Executar de forma sequencial e documentada: Classificar motivos de perda; Criar públicos de recuperação; Criar sequência de reativação; Definir gatilho de retorno ao comercial; Medir taxa de recuperação. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Playbook de recuperação de leads perdidos com segmentação, sequência, gatilhos e taxa de recuperação monitorada.'),
    ('Integrações completas CRM + WhatsApp + E-mail', 'Executar de forma sequencial e documentada: Mapear eventos entre sistemas; Padronizar IDs e origem; Sincronizar mudanças de estágio; Automatizar mensagens transacionais; Criar monitoramento de falhas. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'CRM configurado com campos, etapas, origens, responsabilidades e fluxo ponta a ponta validado.'),
    ('IA para previsões e insights', 'Executar de forma sequencial e documentada: Definir indicadores para previsão; Preparar dados históricos; Criar sinais de risco e oportunidade; Gerar recomendações para gestão; Validar insights contra resultados reais. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Protótipo de insights preditivos com sinais de risco/oportunidade, recomendações e validação contra resultados reais.'),
    ('Padronização de processo comercial', 'Executar de forma sequencial e documentada: Documentar etapas e critérios; Padronizar handoffs; Criar checklists comerciais; Definir SLAs e responsabilidades; Auditar aderência ao processo. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Playbook comercial padronizado com etapas, critérios, handoffs, checklists, SLAs e rotina de auditoria.'),
    ('Escala de campanhas Top Performers', 'Executar de forma sequencial e documentada: Selecionar campanhas vencedoras; Definir teto de escala por canal; Aumentar investimento progressivamente; Monitorar CAC e qualidade; Criar playbook de escala. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Playbook de escala das campanhas vencedoras com limites de investimento, monitoramento de CAC/qualidade e critérios de expansão.'),
    ('Expansão de conteúdos e autoridade', 'Executar de forma sequencial e documentada: Mapear temas e formatos vencedores; Aumentar cadência de produção; Expandir cases e provas sociais; Distribuir conteúdo em múltiplos canais; Medir contribuição para demanda. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Plano de expansão de conteúdo e autoridade com temas vencedores, cadência, distribuição e medição de demanda.'),
    ('Novos segmentos e regiões', 'Executar de forma sequencial e documentada: Selecionar segmentos adjacentes; Validar potencial por dados; Adaptar mensagens e ofertas; Testar regiões prioritárias; Decidir expansão com critérios de CAC e conversão. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Plano de expansão validado por dados, com segmentos/regiões prioritários, mensagens, ofertas, testes e critérios de CAC/conversão.'),
    ('Otimização de ofertas e precificação', 'Executar de forma sequencial e documentada: Analisar elasticidade e conversão; Testar pacotes e ofertas; Avaliar percepção de valor; Medir margem e CAC; Consolidar oferta vencedora. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Oferta/precificação testada e consolidada com evidências de conversão, percepção de valor, margem e CAC.'),
    ('Programa de indicação e prova social ativa', 'Executar de forma sequencial e documentada: Definir mecânica de indicação; Criar incentivos e regras; Estruturar coleta de depoimentos; Automatizar pedidos de indicação; Medir leads e vendas por indicação. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Programa de indicação e prova social operacional, com incentivos, coleta de depoimentos, automação e métricas de origem.'),
    ('Planejamento para expansão contínua', 'Executar de forma sequencial e documentada: Consolidar aprendizados dos 180 dias; Priorizar próximos investimentos; Atualizar roadmap e metas; Definir novos experimentos; Criar ciclo mensal de melhoria contínua. Ao final, reunir evidências, revisar o resultado com o responsável/revisor e registrar decisões, pendências e próximos passos no Growth OS.', 'Roadmap pós-180 dias atualizado com aprendizados, investimentos prioritários, metas, experimentos e ciclo mensal de melhoria.')
)
UPDATE tasks t
SET execution_plan=COALESCE(t.execution_plan,s.execution_plan), deliverable=COALESCE(t.deliverable,s.deliverable), updated_at=NOW()
FROM specs s
WHERE t.title=s.title
  AND (t.execution_plan IS NULL OR t.deliverable IS NULL);
